<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Yugen.Domain\Yugen.Domain.csproj" />
    <ProjectReference Include="..\Yugen.Providers\Yugen.Providers.csproj" />
    <ProjectReference Include="..\Yugen.Data\Yugen.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>