// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yugen.Data;

#nullable disable

namespace Yugen.Data.Migrations
{
    [DbContext(typeof(YugenContext))]
    [Migration("20260511171917_Restructure")]
    partial class Restructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yugen.Domain.Models.Library.Model_DownloadedMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("downloadedMedia");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("SuccessorId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SuccessorId")
                        .IsUnique();

                    b.ToTable("media");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_MediaEpisode", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.HasKey("MediaId", "EpisodeNumber");

                    b.ToTable("mediaEpisodes");
                });

            modelBuilder.Entity("Yugen.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_Media", b =>
                {
                    b.HasOne("Yugen.Domain.Models.Media.Model_Media", "Successor")
                        .WithOne("Predecessor")
                        .HasForeignKey("Yugen.Domain.Models.Media.Model_Media", "SuccessorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Successor");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_MediaEpisode", b =>
                {
                    b.HasOne("Yugen.Domain.Models.Media.Model_Media", "Media")
                        .WithMany("Episodes")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_Media", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Predecessor");
                });
#pragma warning restore 612, 618
        }
    }
}
