// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yugen.Data;

#nullable disable

namespace Yugen.Data.Migrations
{
    [DbContext(typeof(YugenContext))]
    [Migration("20260517160004_TrackTimeOnBookmarks")]
    partial class TrackTimeOnBookmarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yugen.Domain.Models.Bookmarks.Model_Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bookmarkTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Watching"
                        },
                        new
                        {
                            Id = 2,
                            Title = "OnHold"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Planning"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Dropped"
                        });
                });

            modelBuilder.Entity("Yugen.Domain.Models.Bookmarks.Model_UserBookmark", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookmarkId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MediaId", "UserId");

                    b.HasIndex("BookmarkId");

                    b.ToTable("userBookmarks");
                });

            modelBuilder.Entity("Yugen.Domain.Models.History.Model_WatchHistory", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WatchedEpisode")
                        .HasColumnType("integer");

                    b.HasKey("MediaId");

                    b.ToTable("watchHistory");
                });

            modelBuilder.Entity("Yugen.Domain.Models.History.Model_WatchedEpisode", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastWatched")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("WatchPercentage")
                        .HasColumnType("real");

                    b.HasKey("MediaId", "EpisodeNumber");

                    b.ToTable("watchedEpisodes");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Library.Model_DownloadedEpisode", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("JellyfinId")
                        .HasColumnType("text");

                    b.Property<string>("filePath")
                        .HasColumnType("text");

                    b.Property<int?>("sonarrEpisodeId")
                        .HasColumnType("integer");

                    b.HasKey("MediaId", "EpisodeNumber");

                    b.ToTable("sonarrEpisodes");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Library.Model_DownloadedMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MediaId");

                    b.ToTable("downloadedMedia");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Linking.Model_Link", b =>
                {
                    b.Property<int>("anilist_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("anilist_id"));

                    b.Property<int?>("anidb_id")
                        .HasColumnType("integer");

                    b.Property<string>("anime_planet_id")
                        .HasColumnType("text");

                    b.Property<int?>("animecountdown_id")
                        .HasColumnType("integer");

                    b.Property<int?>("animenewsnetwork_id")
                        .HasColumnType("integer");

                    b.Property<int?>("anisearch_id")
                        .HasColumnType("integer");

                    b.Property<string>("imdb_id")
                        .HasColumnType("text");

                    b.Property<int?>("kitsu_id")
                        .HasColumnType("integer");

                    b.Property<int?>("livechart_id")
                        .HasColumnType("integer");

                    b.Property<int?>("mal_id")
                        .HasColumnType("integer");

                    b.Property<int?>("simkl_id")
                        .HasColumnType("integer");

                    b.Property<int?>("themoviedb_id")
                        .HasColumnType("integer");

                    b.Property<int?>("tmdb_season")
                        .HasColumnType("integer");

                    b.Property<int?>("tvdb_id")
                        .HasColumnType("integer");

                    b.Property<int?>("tvdb_season")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("anilist_id");

                    b.ToTable("links");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImage")
                        .HasColumnType("text");

                    b.Property<string>("CardImageLarge")
                        .HasColumnType("text");

                    b.Property<string>("CardImageSmall")
                        .HasColumnType("text");

                    b.Property<string>("Colour")
                        .HasColumnType("text");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("Hydrated")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_MediaEpisode", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EpisodeTitle")
                        .HasColumnType("text");

                    b.Property<bool>("IsFiller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecap")
                        .HasColumnType("boolean");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<int?>("downloadedEpisodeEpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("downloadedEpisodeMediaId")
                        .HasColumnType("integer");

                    b.HasKey("MediaId", "EpisodeNumber");

                    b.HasIndex("downloadedEpisodeMediaId", "downloadedEpisodeEpisodeNumber");

                    b.ToTable("mediaEpisodes");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Model_Config", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("config");
                });

            modelBuilder.Entity("Yugen.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Bookmarks.Model_UserBookmark", b =>
                {
                    b.HasOne("Yugen.Domain.Models.Bookmarks.Model_Bookmark", "Bookmark")
                        .WithMany()
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookmark");
                });

            modelBuilder.Entity("Yugen.Domain.Models.History.Model_WatchedEpisode", b =>
                {
                    b.HasOne("Yugen.Domain.Models.History.Model_WatchHistory", "WatchedHistory")
                        .WithMany("WatchedEpisodes")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchedHistory");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Library.Model_DownloadedEpisode", b =>
                {
                    b.HasOne("Yugen.Domain.Models.Library.Model_DownloadedMedia", "DownloadedMedia")
                        .WithMany("downloadedEpisodes")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownloadedMedia");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_MediaEpisode", b =>
                {
                    b.HasOne("Yugen.Domain.Models.Media.Model_Media", "Media")
                        .WithMany("Episodes")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yugen.Domain.Models.Library.Model_DownloadedEpisode", "downloadedEpisode")
                        .WithMany()
                        .HasForeignKey("downloadedEpisodeMediaId", "downloadedEpisodeEpisodeNumber");

                    b.Navigation("Media");

                    b.Navigation("downloadedEpisode");
                });

            modelBuilder.Entity("Yugen.Domain.Models.History.Model_WatchHistory", b =>
                {
                    b.Navigation("WatchedEpisodes");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Library.Model_DownloadedMedia", b =>
                {
                    b.Navigation("downloadedEpisodes");
                });

            modelBuilder.Entity("Yugen.Domain.Models.Media.Model_Media", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
