// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yugen.Data;

#nullable disable

namespace Yugen.Data.Migrations
{
    [DbContext(typeof(YugenContext))]
    partial class YugenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yugen.Domain.Models.MediaExternalProviderModel", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MediaId", "ProviderType");

                    b.ToTable("mediaExternalProvider");
                });

            modelBuilder.Entity("Yugen.Domain.Models.MediaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("Yugen.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Yugen.Domain.Models.MediaExternalProviderModel", b =>
                {
                    b.HasOne("Yugen.Domain.Models.MediaModel", "Media")
                        .WithMany("externalProviders")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Yugen.Domain.Models.MediaModel", b =>
                {
                    b.Navigation("externalProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
